platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.0'
pod 'JSONKit', '~> 1.5pre'
pod 'SDWebImage-Category', '~> 1.4'
pod 'Reachability', '~> 3.2'
pod 'MJRefresh', '~> 1.4.6'
pod 'SDWebImage', '~>3.7'
pod 'JSONModel', '~> 1.1.0'
pod 'JSONModel', '~> 1.1.0'
pod 'FVCustomAlertView', '~> 0.3.3'